---

- name: Instalacion de influxDB Centos 7, 8
  hosts: terraform 
  remote_user: root

  tasks:
    - name: Inclue variables para directorios 
      include_vars: vars.yaml 

    - name: Descargar ultima version InfluxDB 2021-07-6 # ultima version 2.0 
      # https://portal.influxdata.com/downloads/ 
      yum:
        name: https://dl.influxdata.com/influxdb/releases/influxdb-1.8.6.x86_64.rpm
        state: present
  
    - name: Copiando configuracion base InfluxDB 
      template:
        src: influxdb.j2
        dest: /etc/influxdb/influxdb.conf 

    - name: Creando direcotorios Influxdb meta
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: influxdb
        group: influxdb
        mode: '0755'    
      loop: "{{ path_idb }}"


    - name: Iniciando servicio influxDB 
      ansible.builtin.service:
        name: influxdb
        state: started
        enabled: yes

    - name: Cambia hostname 
      ansible.builtin.hostname:
        name: Srv-DBX 
