---

- name: Configuracion base para equipos Centos 7.X 
  hosts: servers
  remote_user: root

  tasks:
   - name: Epel-Release - paquetes free 
     yum: 
      name: epel-release
      state: present 
   
   - name: Paquetes base 
     yum: 
      name:
       - htop
       - nmap
       - git
       - screen
       - strace 
       - mtr 
       - wget 
       - iftop
       - iotop
       - sysstat
       - telnet
       - unzip
       - zip
       - net-tools
      state: present 
      update_cache: true
  
   - name: Configurando zona horaria America/Santiago
     timezone:
       name: America/Santiago
    
   - name: Instalar telegraf
     yum:
      name: https://dl.influxdata.com/telegraf/releases/telegraf-1.19.0-1.x86_64.rpm
      state: present 
   
   - name: Copiando archivo de config telegraf con variables 
     template:
       src: telegraf.j2
       dest: /tmp/telegraf.conf

   - name: Iniciar servicio telegraf enviara metricas a influxDB
     ansible.builtin.service:
       name: telegraf 
       state: started
       enabled: yes

   - name: Ensure SELinux is set to enforcing mode
     ansible.builtin.lineinfile:
       path: /etc/selinux/config
       regexp: '^SELINUX='
       line: SELINUX=disabled

   - name: Reiniciar el host al terminar de configurar 
     reboot:

# configurar influxdb, primero definir un hostDB para almacenar metricas 
